ALTER TABLE listings ADD COLUMN IF NOT EXISTS reject_reason TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS moderated_by UUID REFERENCES users (id) ON DELETE SET NULL;
